### ISSUE TITLE
Not getting completely dismissed

### ISSUE THREAD

**Issue by jobinsjohn** [hemangshah/Zingle#2]
The message after dismissing shows above the Navigation Bar in inverted state. I think the message is not getting dismissed completely. You can see the text under the navigation bar after dismissing.

<img width="410" alt="screen shot 2018-01-07 at 12 24 35 pm" src="https://user-images.githubusercontent.com/3398498/34647791-f8a85612-f3a5-11e7-8039-1fecb5e01279.png">

**Comment by hemangshah** [comment]
Hi @jobinsjohn, can you share few details like iOS version, iPhone model? Is the view displaying in the attached screenshot is iOS default UINavigationBar or UIView?

**Comment by jobinsjohn** [comment]
iOS Version : 11.2.1(iPhone 8 Plus)

The control is default UINavigationBar.

**Comment by hemangshah** [comment]
@jobinsjohn, Fixed this, try to install/update it with the CocoaPods. Thanks!

**Comment by jobinsjohn** [comment]
Yeah its fixed
