### ISSUE TITLE
Alert Does Not Show

### ISSUE THREAD

**Issue by tadeha** [hemangshah/Zingle#4]
Even though I don't have a UINavigationBar, when I change the default Y position to something else (e.g. 0, 50, 150, 250, 350, ...) I couldn't see the alert bar shown.

**Comment by tadeha** [comment]
BTW the function is calling because I've printed some texts in different functions i.e. yPosForZingal

**Comment by hemangshah** [comment]
@tadeha, thanks for open this! I will keep you posted when I will have some updates.

**Comment by hemangshah** [comment]
@tadeha, unfortunately, this won't be fixed as Zingle was made to show an alert underneath `UINavigationBar`. If your app won't have a `UINavigationController` it will never display for you. Also, please note that it will require a lot of re-work for me to setup it to show even without a `UINavigationController` but then, it's not a good idea that will actually change the originally intended concept. Thanks for using Zingle. Looking forward to hearing from you.

**Comment by tadeha** [comment]
What if my app does use navigation controller and it still doesn't show?

**Comment by hemangshah** [comment]
@tadeha, I need to make it more clear that, it is necessary that each of your `UIViewController`s which should be in a `UINavigationController`s stack, it's not mandatory that you require showing a `UINavigationBar` for each of your `UIViewController`.

**Comment by tadeha** [comment]
Yes, it is exactly how you said.
